-- 권한그룹(super admin group)
INSERT INTO TBL_ADMIN_GROUP (GROUP_NO, GROUP_NAME, GROUP_FLAG, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
                     VALUES (1, 'SUPER ADMIN', null, 'Y', 'N', null, now(), null, now(), null, null);

-- 사용자(super user)
-- 운영 데이타
INSERT INTO TBL_ADMIN_INFO (ADM_NO, GROUP_NO, ADM_ID, PASSWD, ADM_NAME, ADM_INFO, ADM_HPHONE, ADM_HPHONE_HASH, ADM_PHONE, ADM_EMAIL, ADM_EMAIL_HASH, ADM_FLAG, POSITION_CODE, DEPT, MEMO, USE_TF, DEL_TF, LOGIN_DATE, LOGIN_FAIL_CNT, PASSWD_DATE, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES (1, 1, 'administrator', '$2a$10$aCOj1.13evhDwyhSOHwGdetnVFxaGomMlF58fZU7qmkbqXnaaJf66', 'super user', 'A', null, null, null, null, null, 1, null, null, null, 'Y', 'N', null, 0, null, null, now(), null, now(), null, null);

-- 사용자(super user)
-- 개발 데이타
INSERT INTO TBL_ADMIN_INFO (ADM_NO, GROUP_NO, ADM_ID, PASSWD, ADM_NAME, ADM_INFO, ADM_HPHONE, ADM_HPHONE_HASH, ADM_PHONE, ADM_EMAIL, ADM_EMAIL_HASH, ADM_FLAG, POSITION_CODE, DEPT, MEMO, USE_TF, DEL_TF, LOGIN_DATE, LOGIN_FAIL_CNT, PASSWD_DATE, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES (1, 1, 'administrator', '$2a$10$QskTPiL2coVqv2aq8la85Of1JV46qHke1TyMgcSlITjau6rz5utTu', 'super user', 'A', null, null, null, null, null, 1, null, null, null, 'Y', 'N', null, 0, null, null, now(), null, now(), null, null);

-- 메뉴
INSERT INTO TBL_ADMIN_MENU (MENU_NO, MENU_CODE, MENU_NAME, MENU_URL, MENU_DEPTH, MENU_FLAG, MENU_IMG, MENU_IMG_OVER, MENU_ORDER, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE, MENU_PARENT_NO)
VALUES (1, 'C0000', '캠페인 관리', '', 1, null, null, null, 0, 'Y', 'N', 1, now(), 1, now(), null, null, null);
INSERT INTO TBL_ADMIN_MENU (MENU_NO, MENU_CODE, MENU_NAME, MENU_URL, MENU_DEPTH, MENU_FLAG, MENU_IMG, MENU_IMG_OVER, MENU_ORDER, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE, MENU_PARENT_NO)
VALUES (2, 'A0000', '캠페인 분석', '', 1, null, null, null, 1, 'Y', 'N', 1, now(), 1, now(), null, null, null);
INSERT INTO TBL_ADMIN_MENU (MENU_NO, MENU_CODE, MENU_NAME, MENU_URL, MENU_DEPTH, MENU_FLAG, MENU_IMG, MENU_IMG_OVER, MENU_ORDER, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE, MENU_PARENT_NO)
VALUES (3, 'S0000', '설정', '', 1, null, null, null, 2, 'Y', 'N', 1, now(), 1, now(), null, null, null);
INSERT INTO TBL_ADMIN_MENU (MENU_NO, MENU_CODE, MENU_NAME, MENU_URL, MENU_DEPTH, MENU_FLAG, MENU_IMG, MENU_IMG_OVER, MENU_ORDER, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE, MENU_PARENT_NO)
VALUES (4, 'C0001', '캠페인 리스트', '/campaign/list/list.do?acl=C0001', 2, null, '', null, 0, 'Y', 'N', 1, now(), 1, now(), null, null, 1);
INSERT INTO TBL_ADMIN_MENU (MENU_NO, MENU_CODE, MENU_NAME, MENU_URL, MENU_DEPTH, MENU_FLAG, MENU_IMG, MENU_IMG_OVER, MENU_ORDER, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE, MENU_PARENT_NO)
VALUES (5, 'C0002', '캠페인 만들기', '/campaign/base/regist.view?acl=C0002', 2, null, '', null, 1, 'Y', 'N', 1, now(), 1, now(), null, null, 1);
INSERT INTO TBL_ADMIN_MENU (MENU_NO, MENU_CODE, MENU_NAME, MENU_URL, MENU_DEPTH, MENU_FLAG, MENU_IMG, MENU_IMG_OVER, MENU_ORDER, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE, MENU_PARENT_NO)
VALUES (6, 'A0001', '분석 리스트', '/campaign/analysis/list.do?acl=A0001', 2, null, '', null, 0, 'Y', 'N', 1, now(), 1, now(), null, null, 2);
INSERT INTO TBL_ADMIN_MENU (MENU_NO, MENU_CODE, MENU_NAME, MENU_URL, MENU_DEPTH, MENU_FLAG, MENU_IMG, MENU_IMG_OVER, MENU_ORDER, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE, MENU_PARENT_NO)
VALUES (7, 'S0001', '계정 관리', '/settings/account/list.do?acl=S0001', 2, null, '', null, 0, 'Y', 'N', 1, now(), 1, now(), null, null, 3);
INSERT INTO TBL_ADMIN_MENU (MENU_NO, MENU_CODE, MENU_NAME, MENU_URL, MENU_DEPTH, MENU_FLAG, MENU_IMG, MENU_IMG_OVER, MENU_ORDER, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE, MENU_PARENT_NO)
VALUES (8, 'S0002', '메뉴 관리', '/settings/menu/list.do?acl=S0002', 2, null, '', null, 1, 'Y', 'N', 1, now(), 1, now(), null, null, 3);
INSERT INTO TBL_ADMIN_MENU (MENU_NO, MENU_CODE, MENU_NAME, MENU_URL, MENU_DEPTH, MENU_FLAG, MENU_IMG, MENU_IMG_OVER, MENU_ORDER, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE, MENU_PARENT_NO)
VALUES (9, 'S0003', '권한 관리', '/settings/auth/list.do?acl=S0003', 2, null, '', null, 2, 'Y', 'N', 1, now(), 1, now(), null, null, 3);
INSERT INTO TBL_ADMIN_MENU (MENU_NO, MENU_CODE, MENU_NAME, MENU_URL, MENU_DEPTH, MENU_FLAG, MENU_IMG, MENU_IMG_OVER, MENU_ORDER, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE, MENU_PARENT_NO)
VALUES (10, 'S0004', '계정 로그 관리', '/settings/account/log/list.do?acl=S0004', 2, null, '', null, 3, 'Y', 'N', 1, now(), 1, now(), null, null, 3);
INSERT INTO TBL_ADMIN_MENU (MENU_NO, MENU_CODE, MENU_NAME, MENU_URL, MENU_DEPTH, MENU_FLAG, MENU_IMG, MENU_IMG_OVER, MENU_ORDER, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE, MENU_PARENT_NO)
VALUES (11, 'S0005', '접근 IP 관리', '/settings/accept/list.do?acl=S0005', 2, null, '', null, 5, 'Y', 'N', 1, now(), 1, now(), null, null, 3);
INSERT INTO TBL_ADMIN_MENU (MENU_NO, MENU_CODE, MENU_NAME, MENU_URL, MENU_DEPTH, MENU_FLAG, MENU_IMG, MENU_IMG_OVER, MENU_ORDER, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE, MENU_PARENT_NO)
VALUES (12, 'M0000', '내 정보', '/myinfo.do?acl=M0000', 1, null, null, null, 3, 'Y', 'N', 1, now(), 1, now(), null, null, null);

-- 메뉴권한
INSERT INTO TBL_ADMIN_MENU_RIGHT (GROUP_NO, MENU_NO, READ_FLAG, REG_FLAG, UPD_FLAG, DEL_FLAG, FILE_FLAG, REG_ADM, REG_DATE)
VALUES (1, 1, 'Y', 'Y', 'Y', 'Y', 'Y', 1, now());
INSERT INTO TBL_ADMIN_MENU_RIGHT (GROUP_NO, MENU_NO, READ_FLAG, REG_FLAG, UPD_FLAG, DEL_FLAG, FILE_FLAG, REG_ADM, REG_DATE)
VALUES (1, 2, 'Y', 'Y', 'Y', 'Y', 'Y', 1, now());
INSERT INTO TBL_ADMIN_MENU_RIGHT (GROUP_NO, MENU_NO, READ_FLAG, REG_FLAG, UPD_FLAG, DEL_FLAG, FILE_FLAG, REG_ADM, REG_DATE)
VALUES (1, 3, 'Y', 'Y', 'Y', 'Y', 'Y', 1, now());
INSERT INTO TBL_ADMIN_MENU_RIGHT (GROUP_NO, MENU_NO, READ_FLAG, REG_FLAG, UPD_FLAG, DEL_FLAG, FILE_FLAG, REG_ADM, REG_DATE)
VALUES (1, 4, 'Y', 'Y', 'Y', 'Y', 'Y', 1, now());
INSERT INTO TBL_ADMIN_MENU_RIGHT (GROUP_NO, MENU_NO, READ_FLAG, REG_FLAG, UPD_FLAG, DEL_FLAG, FILE_FLAG, REG_ADM, REG_DATE)
VALUES (1, 5, 'Y', 'Y', 'Y', 'Y', 'Y', 1, now());
INSERT INTO TBL_ADMIN_MENU_RIGHT (GROUP_NO, MENU_NO, READ_FLAG, REG_FLAG, UPD_FLAG, DEL_FLAG, FILE_FLAG, REG_ADM, REG_DATE)
VALUES (1, 6, 'Y', 'Y', 'Y', 'Y', 'Y', 1, now());
INSERT INTO TBL_ADMIN_MENU_RIGHT (GROUP_NO, MENU_NO, READ_FLAG, REG_FLAG, UPD_FLAG, DEL_FLAG, FILE_FLAG, REG_ADM, REG_DATE)
VALUES (1, 7, 'Y', 'Y', 'Y', 'Y', 'Y', 1, now());
INSERT INTO TBL_ADMIN_MENU_RIGHT (GROUP_NO, MENU_NO, READ_FLAG, REG_FLAG, UPD_FLAG, DEL_FLAG, FILE_FLAG, REG_ADM, REG_DATE)
VALUES (1, 8, 'Y', 'Y', 'Y', 'Y', 'Y', 1, now());
INSERT INTO TBL_ADMIN_MENU_RIGHT (GROUP_NO, MENU_NO, READ_FLAG, REG_FLAG, UPD_FLAG, DEL_FLAG, FILE_FLAG, REG_ADM, REG_DATE)
VALUES (1, 9, 'Y', 'Y', 'Y', 'Y', 'Y', 1, now());
INSERT INTO TBL_ADMIN_MENU_RIGHT (GROUP_NO, MENU_NO, READ_FLAG, REG_FLAG, UPD_FLAG, DEL_FLAG, FILE_FLAG, REG_ADM, REG_DATE)
VALUES (1, 10, 'Y', 'Y', 'Y', 'Y', 'Y', 1, now());
INSERT INTO TBL_ADMIN_MENU_RIGHT (GROUP_NO, MENU_NO, READ_FLAG, REG_FLAG, UPD_FLAG, DEL_FLAG, FILE_FLAG, REG_ADM, REG_DATE)
VALUES (1, 11, 'Y', 'Y', 'Y', 'Y', 'Y', 1, now());
INSERT INTO TBL_ADMIN_MENU_RIGHT (GROUP_NO, MENU_NO, READ_FLAG, REG_FLAG, UPD_FLAG, DEL_FLAG, FILE_FLAG, REG_ADM, REG_DATE)
VALUES (1, 12, 'Y', 'N', 'Y', 'N', 'N', 1, now());

-- 캠페인 타입
INSERT INTO TBL_CAMPAIGN_BASE_TYPE (BASE_NO, TITLE, CONTENT, CSS_NAME, CONTENT_URI, BASE_ORDER, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES (1, '세로 팝업', '일반적으로 자주 사용되는 세로형 팝업 타입 입니다. 방문자에게 이미지+텍스트 형태의 팝업을 띄워 정보를 제공하고, 특정 페이지로 이동하도록 유도합니다.', 'vertical', '/campaign/campaign.message.vertical', 1, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CAMPAIGN_BASE_TYPE (BASE_NO, TITLE, CONTENT, CSS_NAME, CONTENT_URI, BASE_ORDER, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES (2, '가로 팝업', '일반적으로 자주 사용되는 가로형 팝업 타입 입니다. 방문자에게 이미지+텍스트 형태의 팝업을 띄워 정보를 제공하고, 특정 페이지로 이동하도록 유도합니다.', 'horizontal', '/campaign/campaign.message.horizontal', 2, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CAMPAIGN_BASE_TYPE (BASE_NO, TITLE, CONTENT, CSS_NAME, CONTENT_URI, BASE_ORDER, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES (3, '이미지 플로팅', '좌측 사이드에 이미지로만 구성된 형태의 플로팅 배너를 띄워 간단한 정보가 담긴 알림을 제공하거나, 특정 페이지로 이동하도록 유도합니다.', 'img-floating', '/campaign/campaign.message.image', 3, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CAMPAIGN_BASE_TYPE (BASE_NO, TITLE, CONTENT, CSS_NAME, CONTENT_URI, BASE_ORDER, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES (4, '텍스트 플로팅', '좌측 사이드에 간단한 프로필 이미지와 텍스트로만 구성된 형태의 플로팅 배너를 띄워 간단한 정보가 담긴 알림을 제공하거나, 특정 페이지로 이동하도록 유도합니다.', 'text-floating', '/campaign/campaign.message.text', 4, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CAMPAIGN_BASE_TYPE (BASE_NO, TITLE, CONTENT, CSS_NAME, CONTENT_URI, BASE_ORDER, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES (5, '미니 플로팅', '상단 우측에 랜딩 URL이 포함된 작은 사이즈의 이미지 + 텍스트 형태의 플로팅 배너를 띄워 공지 또는 이벤트 정보를 제공하거나, 특정 페이지로 이동하도록 유도합니다.', 'mini-floating', '/campaign/campaign.message.mini', 5, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CAMPAIGN_BASE_TYPE (BASE_NO, TITLE, CONTENT, CSS_NAME, CONTENT_URI, BASE_ORDER, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES (6, '이미지 띠배너', '상단에 랜딩 URL이 포함된 이미지 형태의 띠배너를 띄워 공지 또는 이벤트 정보를 제공하거나, 특정 페이지로 이동하도록 유도합니다.', 'banner', '/campaign/campaign.message.banner', 6, 'Y', 'N', 1, now(), 1, now(), null, null);

-- 공통코드
INSERT INTO TBL_CODE_PARENT (PCODE, PCODE_NM, PCODE_MEMO, PCODE_SEQ_NO, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('ANAL_SORT_ITEM', '분석용 정렬', '분석용 정렬', 18, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_PARENT (PCODE, PCODE_NM, PCODE_MEMO, PCODE_SEQ_NO, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('APPR_STAT', '사용자 승인상태', '사용자 승인상태', 2, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_PARENT (PCODE, PCODE_NM, PCODE_MEMO, PCODE_SEQ_NO, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('CAM_EXPO_TIME', '노출시간', '노출시간', 9, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_PARENT (PCODE, PCODE_NM, PCODE_MEMO, PCODE_SEQ_NO, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('CAM_GUBUN', '캠페인 구분', '캠페인 구분', 3, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_PARENT (PCODE, PCODE_NM, PCODE_MEMO, PCODE_SEQ_NO, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('CAM_PLACE', '노출위치', '노출위치', 11, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_PARENT (PCODE, PCODE_NM, PCODE_MEMO, PCODE_SEQ_NO, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('CAM_PURPOSE', '캠페인 목표 전환 지점', '캠페인 목표 전환 지점', 4, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_PARENT (PCODE, PCODE_NM, PCODE_MEMO, PCODE_SEQ_NO, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('CAM_STATUS', '캠페인 상태', '캠페인 상태', 17, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_PARENT (PCODE, PCODE_NM, PCODE_MEMO, PCODE_SEQ_NO, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('CAM_TARGET1', '1차타겟', '1차타겟', 5, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_PARENT (PCODE, PCODE_NM, PCODE_MEMO, PCODE_SEQ_NO, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('CAM_TARGET2', '2차타겟', '2차타겟', 7, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_PARENT (PCODE, PCODE_NM, PCODE_MEMO, PCODE_SEQ_NO, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('CAM_USING', '노출 빈도', '노출 빈도', 16, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_PARENT (PCODE, PCODE_NM, PCODE_MEMO, PCODE_SEQ_NO, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('CAM_VIEW_POINT', '노출 시점', '노출 시점', 12, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_PARENT (PCODE, PCODE_NM, PCODE_MEMO, PCODE_SEQ_NO, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('CAM_WEEK', '요일', '요일정보', 8, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_PARENT (PCODE, PCODE_NM, PCODE_MEMO, PCODE_SEQ_NO, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('PAGE_SIZE', '페이지사이즈', '페이지당 건수 설정', 1, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_PARENT (PCODE, PCODE_NM, PCODE_MEMO, PCODE_SEQ_NO, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('SORT_GUBUN', '정렬방식', '정렬방식', 19, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_PARENT (PCODE, PCODE_NM, PCODE_MEMO, PCODE_SEQ_NO, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('TAR1_RETURN', '재방문고객', '1차타겟에서 재방문고객 선택시 설정', 6, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_PARENT (PCODE, PCODE_NM, PCODE_MEMO, PCODE_SEQ_NO, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('TIME_SUB', '상세시간', '상세시간', 10, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_PARENT (PCODE, PCODE_NM, PCODE_MEMO, PCODE_SEQ_NO, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('VIEW_OUT', '페이지 이탈시', '노출 시점이 페이지 이탈시', 15, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_PARENT (PCODE, PCODE_NM, PCODE_MEMO, PCODE_SEQ_NO, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('VIEW_PERCENT', '스크롤 사용', '노출 시점이 스크롤을 사용 할경우', 13, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_PARENT (PCODE, PCODE_NM, PCODE_MEMO, PCODE_SEQ_NO, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('VIEW_SECOND', '초 사용', '노출 시점이 초를 사용 할경우', 14, 'Y', 'N', 1, now(), 1, now(), null, null);

-- 공통코드 상세
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('ANAL_SORT_ITEM', 'END_DATE', '종료일', '종료일', 5, null, null, null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('ANAL_SORT_ITEM', 'ID', 'ID', 'ID', 1, null, null, null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('ANAL_SORT_ITEM', 'LAST_UP_DATE', '최근편집일', '최근 편집일', 6, null, null, null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('ANAL_SORT_ITEM', 'START_DATE', '시작일', '시작일', 4, null, null, null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('ANAL_SORT_ITEM', 'VIEWS', 'Views', 'Views', 3, null, null, null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('ANAL_SORT_ITEM', 'VISIBLE', '노출순위', '노출 순위', 2, null, null, null, null, 'N', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('APPR_STAT', '0', '승인대기', '승인대기', 1, null, null, null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('APPR_STAT', '1', '승인완료', '승인완료', 4, null, null, null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('APPR_STAT', '2', '중지', '중지', 2, null, null, null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('APPR_STAT', '3', '승인거절', '승인거절', 3, null, null, null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('CAM_EXPO_TIME', 'ALL_TIME', 'All Day', '하루종일', 1, '00', '23', null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('CAM_EXPO_TIME', 'DETAIL_TIME', '상세 설정', '상세 설정', 5, null, null, null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('CAM_EXPO_TIME', 'NIGHT_TIME', '심야 시간 (9PM - 6AM)', '심야 시간 (9PM - 6AM)', 4, '21', '06', null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('CAM_EXPO_TIME', 'WORK_TIME', '전화 상담 시간 (9AM - 6PM)', '전화 상담 시간 (9AM - 6PM)', 2, '09', '18', null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('CAM_EXPO_TIME', 'WORK_TIME_OUT', '전화 상담 외 시간 (6PM - 9AM)', '전화 상담 외 시간 (6PM - 9AM)', 3, '18', '09', null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('CAM_GUBUN', 'BD', 'B다이렉트샵', 'B다이렉트샵', 1, null, null, null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('CAM_GUBUN', 'TB', 'B tv 알뜰샵', 'B tv 알뜰샵', 2, null, null, null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('CAM_PLACE', 'ALL_PAGE', 'All Page', '모든 페이지', 1, null, null, null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('CAM_PLACE', 'FIXED_PAGE', '특정 페이지 지정', '특정 페이지 지정', 4, null, null, null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('CAM_PLACE', 'MOBILE_ONLY', 'Only Mobile All Page', 'MOBILE 페이지만 적용', 3, null, null, null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('CAM_PLACE', 'PC_ONLY', 'Only PC All Page', 'PC 페이지만 적용', 2, null, null, null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('CAM_PURPOSE', 'ETC', '기타 페이지 도달 완료', '기타 페이지 도달 완료', 3, null, null, null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('CAM_PURPOSE', 'NONE', '선택 안 함', '선택 안 함', 1, null, null, null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('CAM_PURPOSE', 'ONLINE', '온라인 상담 연락처 남기기 완료 (PC/Mobile)', '온라인 상담 연락처 남기기 완료 (PC/Mobile)', 2, null, null, null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('CAM_STATUS', '1', '작성중', '작성중', 1, null, null, null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('CAM_STATUS', '2', '작성완료', '작성완료', 2, null, null, null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('CAM_STATUS', '3', '일시정지', '일시정지', 3, null, null, null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('CAM_TARGET1', 'ALL', '전체 고객', '전체 고객', 1, 'Y', 'Y', null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('CAM_TARGET1', 'FIXED', '특정 경로로 유입한 고객', '특정 경로로 유입한 고객', 5, 'Y', 'N', null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('CAM_TARGET1', 'NEW', '신규 방문 고객', '신규 방문 고객', 2, 'Y', 'Y', null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('CAM_TARGET1', 'RETURN', '재방문 고객', '재방문 고객', 3, 'Y', 'Y', null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('CAM_TARGET1', 'SEARCH', '사이트 탐색에 관심이 많은 고객', '사이트 탐색에 관심이 많은 고객', 4, 'Y', 'Y', null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('CAM_TARGET2', 'FIXEDWORD', '특정 검색어를 통해 유입한 고객', '특정 검색어를 통해 유입한 고객', 2, null, null, null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('CAM_TARGET2', 'OUTLINK', '외부 링크를 통해 유입한 고객', '외부 링크를 통해 유입한 고객', 1, null, null, null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('CAM_USING', '1', '1회', '1회', 1, null, null, null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('CAM_USING', '2', '2회', '2회', 2, null, null, null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('CAM_USING', '3', '3회', '3회', 3, null, null, null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('CAM_USING', 'CLICK', '메시지 클릭할 때 까지 반복', '메시지 클릭할 때 까지 반복', 4, null, null, null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('CAM_USING', 'UNLIMIT', '제한 없음', '제한 없음', 5, null, null, null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('CAM_VIEW_POINT', 'AT_ONCE', '즉시', '즉시', 1, null, null, null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('CAM_VIEW_POINT', 'BEFORE_OUT', '노출 페이지에서 이탈 직전에', '노출 페이지에서 이탈 직전에', 5, null, null, null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('CAM_VIEW_POINT', 'LOADING', '노출 페이지 로딩 N초 후', '노출 페이지 로딩 N초 후', 3, null, null, null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('CAM_VIEW_POINT', 'NONE_MOVE', '노출 페이지에서 N초 동안 동작이 없을 때', '노출 페이지에서 N초 동안 동작이 없을 때', 4, null, null, null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('CAM_VIEW_POINT', 'PERCENT', '노출 페이지에서 N% 스크롤 시', '노출 페이지에서 N% 스크롤 시', 2, null, null, null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('CAM_WEEK', '0', '일', '일요일', 7, null, null, null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('CAM_WEEK', '1', '월', '월요일', 1, null, null, null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('CAM_WEEK', '2', '화', '화요일', 2, null, null, null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('CAM_WEEK', '3', '수', '수요일', 3, null, null, null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('CAM_WEEK', '4', '목', '목요일', 4, null, null, null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('CAM_WEEK', '5', '금', '금요일', 5, null, null, null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('CAM_WEEK', '6', '토', '토요일', 6, null, null, null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('PAGE_SIZE', '10', '10건씩 보기', '10건씩 보기', 1, null, null, null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('PAGE_SIZE', '30', '30건씩 보기', '30건씩 보기', 2, null, null, null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('PAGE_SIZE', '50', '50건씩 보기', '50건씩 보기', 3, null, null, null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('SORT_GUBUN', 'ASC', '오른차순', '오른차순', 1, null, null, null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('SORT_GUBUN', 'DESC', '내림차순', '내림차순', 2, null, null, null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('TAR1_RETURN', 'TAR1_ALL', '재방문한 전체 고객', '재방문한 전체 고객', 1, null, null, null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('TAR1_RETURN', 'TAR1_EVERY', '최근에 자주 방문한 고객 (최근 7일 동안 사이트에 3번 이상 접속한 고객)', '최근에 자주 방문한 고객 (최근 7일 동안 사이트에 3번 이상 접속한 고객)', 3, null, null, null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('TAR1_RETURN', 'TAR1_FIXED', '특정 페이지에 관심이 많은 고객 (최근 7일 동안 특정 페이지를 3번 이상 방문한 고객)', '특정 페이지에 관심이 많은 고객 (최근 7일 동안 특정 페이지를 3번 이상 방문한 고객)', 2, null, null, null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('TAR1_RETURN', 'TAR1_ONLINE', '온라인 상담 연락처 남기기 이력이 있는 고객', '온라인 상담 연락처 남기기 이력이 있는 고객', 4, null, null, null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('TAR1_RETURN', 'TAR1_NONE', '온라인 상담 연락처 남기기 이력이 없는 고객', '온라인 상담 연락처 남기기 이력이 없는 고객', 5, null, null, null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('TIME_SUB', '0001', '12AM - 1AM', '12AM - 1AM', 1, '00', '01', null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('TIME_SUB', '0102', '1AM - 2AM', '1AM - 2AM', 2, '01', '02', null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('TIME_SUB', '0203', '2AM - 3AM', '2AM - 3AM', 3, '02', '03', null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('TIME_SUB', '0304', '3AM - 4AM', '3AM - 4AM', 4, '03', '04', null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('TIME_SUB', '0405', '4AM - 5AM', '4AM - 5AM', 5, '04', '05', null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('TIME_SUB', '0506', '5AM - 6AM', '5AM - 6AM', 6, '05', '06', null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('TIME_SUB', '0607', '6AM - 7AM', '6AM - 7AM', 7, '06', '07', null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('TIME_SUB', '0708', '7AM - 8AM', '7AM - 8AM', 8, '07', '08', null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('TIME_SUB', '0809', '8AM - 9AM', '8AM - 9AM', 9, '08', '09', null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('TIME_SUB', '0910', '9AM - 10AM', '9AM - 10AM', 10, '09', '10', null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('TIME_SUB', '1011', '10AM - 11AM', '10AM - 11AM', 11, '10', '11', null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('TIME_SUB', '1112', '11AM - 12PM', '11AM - 12PM', 12, '11', '12', null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('TIME_SUB', '1213', '12PM - 1PM', '12PM - 1PM', 13, '12', '13', null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('TIME_SUB', '1314', '1PM - 2PM', '1PM - 2PM', 14, '13', '14', null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('TIME_SUB', '1415', '2PM - 3PM', '2PM - 3PM', 15, '14', '15', null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('TIME_SUB', '1516', '3PM - 4PM', '3PM - 4PM', 16, '15', '16', null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('TIME_SUB', '1617', '4PM - 5PM', '4PM - 5PM', 17, '16', '17', null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('TIME_SUB', '1718', '5PM - 6PM', '5PM - 6PM', 18, '17', '18', null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('TIME_SUB', '1819', '6PM - 7PM', '6PM - 7PM', 19, '18', '19', null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('TIME_SUB', '1920', '7PM - 8PM', '7PM - 8PM', 20, '19', '20', null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('TIME_SUB', '2021', '8PM - 9PM', '8PM - 9PM', 21, '20', '21', null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('TIME_SUB', '2122', '9PM - 10PM', '9PM - 10PM', 22, '21', '22', null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('TIME_SUB', '2223', '10PM - 11PM', '10PM - 11PM', 1, '22', '23', null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('TIME_SUB', '2300', '11PM - 12AM', '11PM - 12AM', 24, '23', '00', null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('VIEW_OUT', 'BACK_BTN', '뒤로가기 버튼 클릭 시', '뒤로가기 버튼 클릭 시', 2, null, null, null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('VIEW_OUT', 'BRS_CLOSE', '브라우저 닫기 버튼 클릭 시', '브라우저 닫기 버튼 클릭 시', 3, null, null, null, null, 'N', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('VIEW_OUT', 'OTHER_PAGE', '사이트 내 다른 메뉴(페이지)로 이동 시', '사이트 내 다른 메뉴(페이지)로 이동 시', 1, null, null, null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('VIEW_PERCENT', '50', '50%', 'VIEW_PERCENT', 1, null, null, null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('VIEW_PERCENT', '70', '70%', '70%', 2, null, null, null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('VIEW_SECOND', '1', '1초', '1초', 1, null, null, null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('VIEW_SECOND', '2', '2초', '2초', 2, null, null, null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('VIEW_SECOND', '3', '3초', '3초', 3, null, null, null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('VIEW_SECOND', '4', '4초', '4초', 4, null, null, null, null, 'Y', 'N', 1, now(), 1, now(), null, null);
INSERT INTO TBL_CODE_DETAIL (PCODE, DCODE, DCODE_NM, DCODE_EXT, DCODE_SEQ_NO, DCODE_EXT_VALUE1, DCODE_EXT_VALUE2, DCODE_EXT_VALUE3, DCODE_EXT_VALUE4, USE_TF, DEL_TF, REG_ADM, REG_DATE, UP_ADM, UP_DATE, DEL_ADM, DEL_DATE)
VALUES ('VIEW_SECOND', '5', '5초', '5초', 5, null, null, null, null, 'Y', 'N', 1, now(), 1, now(), null, null);

